/** Label keys the calendar grid needs from the `calendar` message namespace (server-safe). */
export const CALENDAR_LABEL_KEYS = [
  "horizon14",
  "horizon30",
  "horizon60",
  "horizon90",
  "allGroups",
  "undo",
  "undone",
  "loadedIn",
  "selectHint",
  "nights",
  "night",
  "pricePerNight",
  "save",
  "saved",
  "open",
  "blocked",
  "booked",
  "left",
  "minStay",
  "nightsUnit",
  "advanced",
  "closedToArrival",
  "closedToDeparture",
  "adjustPercent",
  "preview",
  "wouldChange",
  "nothingChanged",
  "apply",
  "applied",
  "cancel",
  "derivedNote",
  "derived",
  "conflictTitle",
  "mine",
  "theirs",
  "keepMine",
  "keepTheirs",
  "loadFailed",
  "editFailed",
  "invalidPrice",
  "today",
] as const;
export type CalendarLabels = Record<(typeof CALENDAR_LABEL_KEYS)[number], string>;
