/**
 * Tenancy declaration for every table (INV-10). The RLS integration test
 * enumerates the Drizzle schema and fails on any table missing here, and on any
 * `org` table without `org_id NOT NULL` and a policy.
 *
 * - `org`: has `org_id`, RLS forced, policy `org_id = current_setting('app.org_id')`
 * - `org-root`: the organization table itself; policy on `id`
 * - `global`: no tenant column (users, sessions); access is mediated by the application
 */
export type Tenancy = "org" | "org-root" | "global";

export const TENANCY: Readonly<Record<string, Tenancy>> = {
  organization: "org-root",
  org_key: "org",
  property_group: "org",
  property: "org",
  property_group_membership: "org",
  custom_role: "org",
  grant: "org",
  invitation: "org",
  service_account: "org",
  api_key: "org",
  audit_log: "org",
  outbox_event: "org",
  processed_event: "org",
  otb_snapshot: "org",
  room_type: "org",
  rate_plan: "org",
  availability_day: "org",
  rate_day: "org",
  sync_operation: "org",
  inbound_webhook: "org",
  guest: "org",
  booking: "org",
  booking_revision: "org",
  booking_room: "org",
  booking_room_day: "org",
  payment_instrument: "org",
  unit: "org",
  property_template: "org",
  property_provisioning: "org",
  season: "org",
  policy: "org",
  tax_set: "org",
  photo: "org",
  availability_rule: "org",
  bulk_operation: "org",
  channel_account: "org",
  channel_connection: "org",
  channel_mapping: "org",
  channel_event: "org",
  unit_block: "org",
  crew: "org",
  crew_member: "org",
  checklist: "org",
  turnover_task: "org",
  maintenance_issue: "org",
  access_credential: "org",
  note: "org",
  folio: "org",
  folio_line: "org",
  payment: "org",
  invoice_sequence: "org",
  invoice: "org",
  daily_close: "org",
  saved_view: "org",
  booking_acknowledgement: "org",
  stay_state: "org",
  message_thread: "org",
  message: "org",
  attachment: "org",
  message_template: "org",
  automation_rule: "org",
  automation_run: "org",
  review: "org",
  review_response: "org",
  owner: "org",
  owner_document: "org",
  owner_agreement: "org",
  owner_expense: "org",
  owner_statement: "org",
  owner_statement_line: "org",
  owner_statement_night: "org",
  owner_payout: "org",
  fact_room_night: "org",
  fact_booking: "org",
  agg_daily_kpi: "org",
  budget: "org",
  alert: "org",
  report_schedule: "org",
  booking_engine_settings: "org",
  booking_hold: "org",
  promo_code: "org",
  extra: "org",
  guest_session: "org",
  pre_checkin: "org",
  user: "global",
  session: "global",
  magic_link: "global",
  org_membership: "global",
  // M8 (spec 12)
  plan: "global",
  subscription: "org",
  usage_record: "org",
  billing_invoice: "org",
  platform_operator: "global",
  operator_audit_log: "global",
  feature_flag: "global",
  announcement: "global",
  impersonation_session: "org",
  support_access_grant: "org",
  plugin: "org",
  plugin_delivery: "org",
  data_export: "org",
  platform_job_request: "global",
};

export const ORG_TABLES = Object.entries(TENANCY)
  .filter(([, t]) => t === "org")
  .map(([name]) => name);
